import type { Metadata } from "next";
import { WebSocketProvider } from "./providers/WebSocketProvider";
import GameProvider from "./providers/GameProvider";
import { PrimeReactProvider } from 'primereact/api';
import "./globals.css";
import 'primereact/resources/themes/saga-orange/theme.css';


export const metadata: Metadata = {
  title: "Category Game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PrimeReactProvider>
          <WebSocketProvider>
            <GameProvider>
              {children}
            </GameProvider>
          </WebSocketProvider>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
